use crate::metadata::*;
pub const METADATA: Metadata = Metadata {
    name: "MCXN947_cm33_core0",
    pins: PINS,
    peripherals: PERIPHERALS,
    interrupts: INTERRUPTS,
};
pub const PINS: &[Pin] = &[
    Pin {
        name: "P5_0",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P5_1",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P5_2",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P5_3",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P5_4",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P5_5",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P5_6",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P5_7",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P5_8",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P5_9",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_0",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_1",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_2",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_3",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_4",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_5",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_6",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_7",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_8",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_9",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_10",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_11",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_12",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_13",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_14",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_15",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_16",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_17",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_18",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_19",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_20",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_21",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_22",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_23",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_24",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_25",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_26",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_27",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_28",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_29",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_30",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_31",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_0",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_1",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_2",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_3",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_4",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_5",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_6",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_7",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_8",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_9",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_10",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_11",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_12",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_13",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_14",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_15",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_16",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_17",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_18",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_19",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_20",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_21",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_22",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_23",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_30",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P1_31",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_0",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_1",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_2",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_3",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_4",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_5",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_6",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_7",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_8",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_9",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_10",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P2_11",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_0",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_1",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_2",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_3",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_4",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_5",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_6",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_7",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_8",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_9",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_10",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_11",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_12",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_13",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_14",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_15",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_16",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_17",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_18",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_19",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_20",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_21",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_22",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_23",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_0",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_1",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_2",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_3",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_4",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_5",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_6",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_7",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_12",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_13",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_14",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_15",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_16",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_17",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_18",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_19",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_20",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_21",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_22",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P4_23",
        iomuxc: None,
        feature: None,
    },
];
pub const PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "SYSCON0",
        address: 0x40000000,
        driver_name: "mcxn/SYSCON",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PINT0",
        address: 0x40004000,
        driver_name: "mcxn/PINT0",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "INPUTMUX0",
        address: 0x40006000,
        driver_name: "mcxn/INPUTMUX0",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CTIMER0",
        address: 0x4000C000,
        driver_name: "mcx/CTIMER",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CTIMER1",
        address: 0x4000D000,
        driver_name: "mcx/CTIMER",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CTIMER2",
        address: 0x4000E000,
        driver_name: "mcx/CTIMER",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CTIMER3",
        address: 0x4000F000,
        driver_name: "mcx/CTIMER",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CTIMER4",
        address: 0x40010000,
        driver_name: "mcx/CTIMER",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FREQME0",
        address: 0x40011000,
        driver_name: "mcxn/FREQME",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "UTICK0",
        address: 0x40012000,
        driver_name: "mcxn/UTICK",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "MRT0",
        address: 0x40013000,
        driver_name: "mcxn/MRT",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "WWDT0",
        address: 0x40016000,
        driver_name: "mcx/WWDT",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "WWDT1",
        address: 0x40017000,
        driver_name: "mcx/WWDT",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CACHE64_CTRL0",
        address: 0x4001B000,
        driver_name: "mcxn/CACHE64Ctrl::CACHE64_CTRL",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CACHE64_POLSEL0",
        address: 0x4001B000,
        driver_name: "mcxn/CACHE64Polsel::CACHE64_POLSEL",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "I3C0",
        address: 0x40021000,
        driver_name: "mcxn/I3C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "I3C1",
        address: 0x40022000,
        driver_name: "mcxn/I3C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GDET0",
        address: 0x40024000,
        driver_name: "mcxn/GDET",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GDET1",
        address: 0x40025000,
        driver_name: "mcxn/GDET",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ITRC0",
        address: 0x40026000,
        driver_name: "mcxn/ITRC0",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PKC0",
        address: 0x4002B000,
        driver_name: "mcxn/PKC0",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF",
        address: 0x4002C000,
        driver_name: "mcxn/PUF",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_ALIAS1",
        address: 0x4002D000,
        driver_name: "mcxn/PUF",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_ALIAS2",
        address: 0x4002E000,
        driver_name: "mcxn/PUF",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_ALIAS3",
        address: 0x4002F000,
        driver_name: "mcxn/PUF",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_CTRL",
        address: 0x4002C000,
        driver_name: "mcxn/PUF_CTRL",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_CTRL_ALIAS1",
        address: 0x4002D000,
        driver_name: "mcxn/PUF_CTRL",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_CTRL_ALIAS2",
        address: 0x4002E000,
        driver_name: "mcxn/PUF_CTRL",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_CTRL_ALIAS3",
        address: 0x4002F000,
        driver_name: "mcxn/PUF_CTRL",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "BSP32_0",
        address: 0x40032000,
        driver_name: "mcxn/BSP32",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SMARTDMA0",
        address: 0x40033000,
        driver_name: "mcxn/SMARTDMA",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PLU0",
        address: 0x40034000,
        driver_name: "mcxn/PLU0",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO5",
        address: 0x40040000,
        driver_name: "mcx/GPIO",
        signals: &[
            Signal {
                name: "0",
                pins: &[SignalPin {
                    pin: "P5_0",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "1",
                pins: &[SignalPin {
                    pin: "P5_1",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "2",
                pins: &[SignalPin {
                    pin: "P5_2",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "3",
                pins: &[SignalPin {
                    pin: "P5_3",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "4",
                pins: &[SignalPin {
                    pin: "P5_4",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "5",
                pins: &[SignalPin {
                    pin: "P5_5",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "6",
                pins: &[SignalPin {
                    pin: "P5_6",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "7",
                pins: &[SignalPin {
                    pin: "P5_7",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "8",
                pins: &[SignalPin {
                    pin: "P5_8",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "9",
                pins: &[SignalPin {
                    pin: "P5_9",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
        ],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO5_ALIAS1",
        address: 0x40041000,
        driver_name: "mcx/GPIO",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT5",
        address: 0x40042000,
        driver_name: "mcx/PORT",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FMU0",
        address: 0x40043000,
        driver_name: "mcxn/FMU",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FMU0TEST",
        address: 0x40043000,
        driver_name: "mcxn/FMU0TEST",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SCG0",
        address: 0x40044000,
        driver_name: "mcxn/SCG",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SPC0",
        address: 0x40045000,
        driver_name: "mcxn/SPC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "WUU0",
        address: 0x40046000,
        driver_name: "mcxn/WUU",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMC0",
        address: 0x40048000,
        driver_name: "mcxn/CMC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "OSTIMER0",
        address: 0x40049000,
        driver_name: "mcxn/OSTIMER",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPTMR0",
        address: 0x4004A000,
        driver_name: "mcxn/LPTMR",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPTMR1",
        address: 0x4004B000,
        driver_name: "mcxn/LPTMR",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "RTC0",
        address: 0x4004C000,
        driver_name: "mcx/RTC5xx::Rtc",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "RTC_SUBSYSTEM0",
        address: 0x4004C000,
        driver_name: "mcxn/RTC_SUBSYSTEM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "TSI0",
        address: 0x40050000,
        driver_name: "mcxn/TSI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMP0",
        address: 0x40051000,
        driver_name: "mcxn/CMP",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMP1",
        address: 0x40052000,
        driver_name: "mcxn/CMP",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMP2",
        address: 0x40053000,
        driver_name: "mcxn/CMP",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ELS",
        address: 0x40054000,
        driver_name: "mcxn/ELS",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ELS_ALIAS1",
        address: 0x40055000,
        driver_name: "mcxn/ELS",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ELS_ALIAS2",
        address: 0x40056000,
        driver_name: "mcxn/ELS",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ELS_ALIAS3",
        address: 0x40057000,
        driver_name: "mcxn/ELS",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "TDET0",
        address: 0x40058000,
        driver_name: "mcxn/TDET",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "VBAT0",
        address: 0x40059000,
        driver_name: "mcxn/VBAT",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EIM0",
        address: 0x4005B000,
        driver_name: "mcxn/EIM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ERM0",
        address: 0x4005C000,
        driver_name: "mcxn/ERM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "INTM0",
        address: 0x4005D000,
        driver_name: "mcxn/INTM0",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DMA0",
        address: 0x40080000,
        driver_name: "mcxn/DMA::DMA16",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DMA1",
        address: 0x400A0000,
        driver_name: "mcxn/DMA::DMA16",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EDMA_0_TCD",
        address: 0x40081000,
        driver_name: "mcxn/EDMA_TCD::TCD16",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SCT0",
        address: 0x40091000,
        driver_name: "mcxn/SCT",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI0",
        address: 0x40092000,
        driver_name: "mcxn/LPSPI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI1",
        address: 0x40093000,
        driver_name: "mcxn/LPSPI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI2",
        address: 0x40094000,
        driver_name: "mcxn/LPSPI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI3",
        address: 0x40095000,
        driver_name: "mcxn/LPSPI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI4",
        address: 0x400B4000,
        driver_name: "mcxn/LPSPI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI5",
        address: 0x400B5000,
        driver_name: "mcxn/LPSPI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI6",
        address: 0x400B6000,
        driver_name: "mcxn/LPSPI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI7",
        address: 0x400B7000,
        driver_name: "mcxn/LPSPI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI8",
        address: 0x400B8000,
        driver_name: "mcxn/LPSPI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI9",
        address: 0x400B9000,
        driver_name: "mcxn/LPSPI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART0",
        address: 0x40092000,
        driver_name: "mcxn/LPUART",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART1",
        address: 0x40093000,
        driver_name: "mcxn/LPUART",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART2",
        address: 0x40094000,
        driver_name: "mcxn/LPUART",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART3",
        address: 0x40095000,
        driver_name: "mcxn/LPUART",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART4",
        address: 0x400B4000,
        driver_name: "mcxn/LPUART",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART5",
        address: 0x400B5000,
        driver_name: "mcxn/LPUART",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART6",
        address: 0x400B6000,
        driver_name: "mcxn/LPUART",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART7",
        address: 0x400B7000,
        driver_name: "mcxn/LPUART",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART8",
        address: 0x400B8000,
        driver_name: "mcxn/LPUART",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART9",
        address: 0x400B9000,
        driver_name: "mcxn/LPUART",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM0",
        address: 0x40092000,
        driver_name: "mcxn/LP_FLEXCOMM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM1",
        address: 0x40093000,
        driver_name: "mcxn/LP_FLEXCOMM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM2",
        address: 0x40094000,
        driver_name: "mcxn/LP_FLEXCOMM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM3",
        address: 0x40095000,
        driver_name: "mcxn/LP_FLEXCOMM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM4",
        address: 0x400B4000,
        driver_name: "mcxn/LP_FLEXCOMM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM5",
        address: 0x400B5000,
        driver_name: "mcxn/LP_FLEXCOMM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM6",
        address: 0x400B6000,
        driver_name: "mcxn/LP_FLEXCOMM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM7",
        address: 0x400B7000,
        driver_name: "mcxn/LP_FLEXCOMM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM8",
        address: 0x400B8000,
        driver_name: "mcxn/LP_FLEXCOMM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM9",
        address: 0x400B9000,
        driver_name: "mcxn/LP_FLEXCOMM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C0",
        address: 0x40092800,
        driver_name: "mcxn/LPI2C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C1",
        address: 0x40093800,
        driver_name: "mcxn/LPI2C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C2",
        address: 0x40094800,
        driver_name: "mcxn/LPI2C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C3",
        address: 0x40095800,
        driver_name: "mcxn/LPI2C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C4",
        address: 0x400B4800,
        driver_name: "mcxn/LPI2C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C5",
        address: 0x400B5800,
        driver_name: "mcxn/LPI2C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C6",
        address: 0x400B6800,
        driver_name: "mcxn/LPI2C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C7",
        address: 0x400B7800,
        driver_name: "mcxn/LPI2C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C8",
        address: 0x400B8800,
        driver_name: "mcxn/LPI2C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C9",
        address: 0x400B9800,
        driver_name: "mcxn/LPI2C",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO0",
        address: 0x40096000,
        driver_name: "mcx/GPIO",
        signals: &[
            Signal {
                name: "0",
                pins: &[SignalPin {
                    pin: "P0_0",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "1",
                pins: &[SignalPin {
                    pin: "P0_1",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "2",
                pins: &[SignalPin {
                    pin: "P0_2",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "3",
                pins: &[SignalPin {
                    pin: "P0_3",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "4",
                pins: &[SignalPin {
                    pin: "P0_4",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "5",
                pins: &[SignalPin {
                    pin: "P0_5",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "6",
                pins: &[SignalPin {
                    pin: "P0_6",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "7",
                pins: &[SignalPin {
                    pin: "P0_7",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "8",
                pins: &[SignalPin {
                    pin: "P0_8",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "9",
                pins: &[SignalPin {
                    pin: "P0_9",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "10",
                pins: &[SignalPin {
                    pin: "P0_10",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "11",
                pins: &[SignalPin {
                    pin: "P0_11",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "12",
                pins: &[SignalPin {
                    pin: "P0_12",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "13",
                pins: &[SignalPin {
                    pin: "P0_13",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "14",
                pins: &[SignalPin {
                    pin: "P0_14",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "15",
                pins: &[SignalPin {
                    pin: "P0_15",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "16",
                pins: &[SignalPin {
                    pin: "P0_16",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "17",
                pins: &[SignalPin {
                    pin: "P0_17",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "18",
                pins: &[SignalPin {
                    pin: "P0_18",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "19",
                pins: &[SignalPin {
                    pin: "P0_19",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "20",
                pins: &[SignalPin {
                    pin: "P0_20",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "21",
                pins: &[SignalPin {
                    pin: "P0_21",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "22",
                pins: &[SignalPin {
                    pin: "P0_22",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "23",
                pins: &[SignalPin {
                    pin: "P0_23",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "24",
                pins: &[SignalPin {
                    pin: "P0_24",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "25",
                pins: &[SignalPin {
                    pin: "P0_25",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "26",
                pins: &[SignalPin {
                    pin: "P0_26",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "27",
                pins: &[SignalPin {
                    pin: "P0_27",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "28",
                pins: &[SignalPin {
                    pin: "P0_28",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "29",
                pins: &[SignalPin {
                    pin: "P0_29",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "30",
                pins: &[SignalPin {
                    pin: "P0_30",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "31",
                pins: &[SignalPin {
                    pin: "P0_31",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
        ],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO0_ALIAS1",
        address: 0x40097000,
        driver_name: "mcx/GPIO",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO1",
        address: 0x40098000,
        driver_name: "mcx/GPIO",
        signals: &[
            Signal {
                name: "0",
                pins: &[SignalPin {
                    pin: "P1_0",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "1",
                pins: &[SignalPin {
                    pin: "P1_1",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "2",
                pins: &[SignalPin {
                    pin: "P1_2",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "3",
                pins: &[SignalPin {
                    pin: "P1_3",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "4",
                pins: &[SignalPin {
                    pin: "P1_4",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "5",
                pins: &[SignalPin {
                    pin: "P1_5",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "6",
                pins: &[SignalPin {
                    pin: "P1_6",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "7",
                pins: &[SignalPin {
                    pin: "P1_7",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "8",
                pins: &[SignalPin {
                    pin: "P1_8",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "9",
                pins: &[SignalPin {
                    pin: "P1_9",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "10",
                pins: &[SignalPin {
                    pin: "P1_10",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "11",
                pins: &[SignalPin {
                    pin: "P1_11",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "12",
                pins: &[SignalPin {
                    pin: "P1_12",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "13",
                pins: &[SignalPin {
                    pin: "P1_13",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "14",
                pins: &[SignalPin {
                    pin: "P1_14",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "15",
                pins: &[SignalPin {
                    pin: "P1_15",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "16",
                pins: &[SignalPin {
                    pin: "P1_16",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "17",
                pins: &[SignalPin {
                    pin: "P1_17",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "18",
                pins: &[SignalPin {
                    pin: "P1_18",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "19",
                pins: &[SignalPin {
                    pin: "P1_19",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "20",
                pins: &[SignalPin {
                    pin: "P1_20",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "21",
                pins: &[SignalPin {
                    pin: "P1_21",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "22",
                pins: &[SignalPin {
                    pin: "P1_22",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "23",
                pins: &[SignalPin {
                    pin: "P1_23",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "30",
                pins: &[SignalPin {
                    pin: "P1_30",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "31",
                pins: &[SignalPin {
                    pin: "P1_31",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
        ],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO1_ALIAS1",
        address: 0x40099000,
        driver_name: "mcx/GPIO",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO2",
        address: 0x4009A000,
        driver_name: "mcx/GPIO",
        signals: &[
            Signal {
                name: "0",
                pins: &[SignalPin {
                    pin: "P2_0",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "1",
                pins: &[SignalPin {
                    pin: "P2_1",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "2",
                pins: &[SignalPin {
                    pin: "P2_2",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "3",
                pins: &[SignalPin {
                    pin: "P2_3",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "4",
                pins: &[SignalPin {
                    pin: "P2_4",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "5",
                pins: &[SignalPin {
                    pin: "P2_5",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "6",
                pins: &[SignalPin {
                    pin: "P2_6",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "7",
                pins: &[SignalPin {
                    pin: "P2_7",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "8",
                pins: &[SignalPin {
                    pin: "P2_8",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "9",
                pins: &[SignalPin {
                    pin: "P2_9",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "10",
                pins: &[SignalPin {
                    pin: "P2_10",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "11",
                pins: &[SignalPin {
                    pin: "P2_11",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
        ],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO2_ALIAS1",
        address: 0x4009B000,
        driver_name: "mcx/GPIO",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO3",
        address: 0x4009C000,
        driver_name: "mcx/GPIO",
        signals: &[
            Signal {
                name: "0",
                pins: &[SignalPin {
                    pin: "P3_0",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "1",
                pins: &[SignalPin {
                    pin: "P3_1",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "2",
                pins: &[SignalPin {
                    pin: "P3_2",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "3",
                pins: &[SignalPin {
                    pin: "P3_3",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "4",
                pins: &[SignalPin {
                    pin: "P3_4",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "5",
                pins: &[SignalPin {
                    pin: "P3_5",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "6",
                pins: &[SignalPin {
                    pin: "P3_6",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "7",
                pins: &[SignalPin {
                    pin: "P3_7",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "8",
                pins: &[SignalPin {
                    pin: "P3_8",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "9",
                pins: &[SignalPin {
                    pin: "P3_9",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "10",
                pins: &[SignalPin {
                    pin: "P3_10",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "11",
                pins: &[SignalPin {
                    pin: "P3_11",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "12",
                pins: &[SignalPin {
                    pin: "P3_12",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "13",
                pins: &[SignalPin {
                    pin: "P3_13",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "14",
                pins: &[SignalPin {
                    pin: "P3_14",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "15",
                pins: &[SignalPin {
                    pin: "P3_15",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "16",
                pins: &[SignalPin {
                    pin: "P3_16",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "17",
                pins: &[SignalPin {
                    pin: "P3_17",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "18",
                pins: &[SignalPin {
                    pin: "P3_18",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "19",
                pins: &[SignalPin {
                    pin: "P3_19",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "20",
                pins: &[SignalPin {
                    pin: "P3_20",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "21",
                pins: &[SignalPin {
                    pin: "P3_21",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "22",
                pins: &[SignalPin {
                    pin: "P3_22",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "23",
                pins: &[SignalPin {
                    pin: "P3_23",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
        ],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO3_ALIAS1",
        address: 0x4009D000,
        driver_name: "mcx/GPIO",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO4",
        address: 0x4009E000,
        driver_name: "mcx/GPIO",
        signals: &[
            Signal {
                name: "0",
                pins: &[SignalPin {
                    pin: "P4_0",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "1",
                pins: &[SignalPin {
                    pin: "P4_1",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "2",
                pins: &[SignalPin {
                    pin: "P4_2",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "3",
                pins: &[SignalPin {
                    pin: "P4_3",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "4",
                pins: &[SignalPin {
                    pin: "P4_4",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "5",
                pins: &[SignalPin {
                    pin: "P4_5",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "6",
                pins: &[SignalPin {
                    pin: "P4_6",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "7",
                pins: &[SignalPin {
                    pin: "P4_7",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "12",
                pins: &[SignalPin {
                    pin: "P4_12",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "13",
                pins: &[SignalPin {
                    pin: "P4_13",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "14",
                pins: &[SignalPin {
                    pin: "P4_14",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "15",
                pins: &[SignalPin {
                    pin: "P4_15",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "16",
                pins: &[SignalPin {
                    pin: "P4_16",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "17",
                pins: &[SignalPin {
                    pin: "P4_17",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "18",
                pins: &[SignalPin {
                    pin: "P4_18",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "19",
                pins: &[SignalPin {
                    pin: "P4_19",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "20",
                pins: &[SignalPin {
                    pin: "P4_20",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "21",
                pins: &[SignalPin {
                    pin: "P4_21",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "22",
                pins: &[SignalPin {
                    pin: "P4_22",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "23",
                pins: &[SignalPin {
                    pin: "P4_23",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
        ],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO4_ALIAS1",
        address: 0x4009F000,
        driver_name: "mcx/GPIO",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EDMA_1_TCD",
        address: 0x400A1000,
        driver_name: "mcxn/EDMA_TCD::TCD16",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SEMA42_0",
        address: 0x400B1000,
        driver_name: "mcxn/SEMA42",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "MAILBOX",
        address: 0x400B2000,
        driver_name: "mcxn/MAILBOX",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CDOG0",
        address: 0x400BB000,
        driver_name: "mcxn/CDOG",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CDOG1",
        address: 0x400BC000,
        driver_name: "mcxn/CDOG",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DM0",
        address: 0x400BD000,
        driver_name: "mcxn/DM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "POWERQUAD",
        address: 0x400BF000,
        driver_name: "mcxn/POWERQUAD",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EWM0",
        address: 0x400C0000,
        driver_name: "mcxn/EWM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMX_PERFMON0",
        address: 0x400C1000,
        driver_name: "mcxn/CMX_PERFMON",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMX_PERFMON1",
        address: 0x400C2000,
        driver_name: "mcxn/CMX_PERFMON",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "TRDC",
        address: 0x400C7000,
        driver_name: "mcxn/TRDC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FLEXSPI0",
        address: 0x400C8000,
        driver_name: "mcxn/FLEXSPI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "OTPC0",
        address: 0x400C9000,
        driver_name: "mcxn/OTPC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CRC0",
        address: 0x400CB000,
        driver_name: "mcxn/CRC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "NPX0",
        address: 0x400CC000,
        driver_name: "mcxn/NPX",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PWM0",
        address: 0x400CE000,
        driver_name: "mcxn/PWM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PWM1",
        address: 0x400D0000,
        driver_name: "mcxn/PWM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "QDC0",
        address: 0x400CF000,
        driver_name: "mcxn/QDC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "QDC1",
        address: 0x400D1000,
        driver_name: "mcxn/QDC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EVTG0",
        address: 0x400D2000,
        driver_name: "mcxn/EVTG",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CAN0",
        address: 0x400D4000,
        driver_name: "mcxn/CAN",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CAN1",
        address: 0x400D8000,
        driver_name: "mcxn/CAN",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBDCD0",
        address: 0x400DC000,
        driver_name: "mcxn/USBDCD",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBFS0",
        address: 0x400DD000,
        driver_name: "mcxn/USBFS",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ENET0",
        address: 0x40100000,
        driver_name: "mcxn/ENET",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EMVSIM0",
        address: 0x40103000,
        driver_name: "mcxn/EMVSIM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EMVSIM1",
        address: 0x40104000,
        driver_name: "mcxn/EMVSIM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FLEXIO0",
        address: 0x40105000,
        driver_name: "mcxn/FLEXIO",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SAI0",
        address: 0x40106000,
        driver_name: "mcxn/SAI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SAI1",
        address: 0x40107000,
        driver_name: "mcxn/SAI",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SINC0",
        address: 0x40108000,
        driver_name: "mcxn/SINC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USDHC0",
        address: 0x40109000,
        driver_name: "mcxn/USDHC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBPHY",
        address: 0x4010A000,
        driver_name: "mcxn/USBPHY",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBHS1_PHY_DCD",
        address: 0x4010A800,
        driver_name: "mcxn/USBHS1_PHY_DCD",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBHS1__USBC",
        address: 0x4010B000,
        driver_name: "mcxn/USBHS1__USBC::USBHS1_USBC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBHS1__USBNC",
        address: 0x4010B200,
        driver_name: "mcxn/USBHS1__USBNC::USBHS1_USBNC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PDM",
        address: 0x4010C000,
        driver_name: "mcxn/PDM",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ADC0",
        address: 0x4010D000,
        driver_name: "mcxn/ADC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ADC1",
        address: 0x4010E000,
        driver_name: "mcxn/ADC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DAC0",
        address: 0x4010F000,
        driver_name: "mcx/DAC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DAC1",
        address: 0x40112000,
        driver_name: "mcx/DAC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "OPAMP0",
        address: 0x40110000,
        driver_name: "mcxn/OPAMP",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "OPAMP1",
        address: 0x40113000,
        driver_name: "mcxn/OPAMP",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "OPAMP2",
        address: 0x40115000,
        driver_name: "mcxn/OPAMP",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "VREF0",
        address: 0x40111000,
        driver_name: "mcxn/VREF",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DAC2",
        address: 0x40114000,
        driver_name: "mcxn/DAC2",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT0",
        address: 0x40116000,
        driver_name: "mcx/PORT",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT1",
        address: 0x40117000,
        driver_name: "mcx/PORT",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT2",
        address: 0x40118000,
        driver_name: "mcx/PORT",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT3",
        address: 0x40119000,
        driver_name: "mcx/PORT",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT4",
        address: 0x4011A000,
        driver_name: "mcx/PORT",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "AHBSC",
        address: 0x40120000,
        driver_name: "mcxn/AHBSC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "AHBSC_ALIAS1",
        address: 0x40121000,
        driver_name: "mcxn/AHBSC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "AHBSC_ALIAS2",
        address: 0x40122000,
        driver_name: "mcxn/AHBSC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "AHBSC_ALIAS3",
        address: 0x40123000,
        driver_name: "mcxn/AHBSC",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SCnSCB",
        address: 0xE000E000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SysTick0",
        address: 0xE000E010,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "NVIC",
        address: 0xE000E100,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SCB",
        address: 0xE000ED00,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "MPU",
        address: 0xE000ED90,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SAU",
        address: 0xE000EDD0,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
];
pub const INTERRUPTS: &[(&str, u32)] = &[
    ("ETB0", 149u32),
    ("CTI0", 155u32),
    ("PINT0", 47u32),
    ("CTIMER0", 31u32),
    ("CTIMER1", 32u32),
    ("CTIMER2", 34u32),
    ("CTIMER3", 55u32),
    ("CTIMER4", 56u32),
    ("FREQME", 71u32),
    ("UTICK0", 29u32),
    ("MRT0", 30u32),
    ("WWDT0", 152u32),
    ("WWDT1", 153u32),
    ("I3C0", 95u32),
    ("I3C1", 96u32),
    ("GDET", 98u32),
    ("ITRC0", 132u32),
    ("PKC", 74u32),
    ("PKC_ERR", 135u32),
    ("PUF", 75u32),
    ("BSP32", 133u32),
    ("SMARTDMA", 53u32),
    ("PLU", 70u32),
    ("GPIO50", 27u32),
    ("GPIO51", 28u32),
    ("PORT_EFT", 148u32),
    ("FMU0", 138u32),
    ("SCG", 145u32),
    ("SPC", 146u32),
    ("WUU", 147u32),
    ("CMC0", 154u32),
    ("OS_EVENT", 57u32),
    ("LPTMR0", 143u32),
    ("LPTMR1", 144u32),
    ("RTC", 52u32),
    ("TSI_END_OF_SCAN", 101u32),
    ("TSI_OUT_OF_SCAN", 102u32),
    ("HSCMP0", 109u32),
    ("HSCMP1", 110u32),
    ("HSCMP2", 111u32),
    ("ELS", 73u32),
    ("ELS_ERR", 134u32),
    ("VBAT0", 99u32),
    ("ERM_SINGLE_BIT_ERROR", 136u32),
    ("ERM_MULTI_BIT_ERROR", 137u32),
    ("EDMA_0_CH0", 1u32),
    ("EDMA_0_CH1", 2u32),
    ("EDMA_0_CH2", 3u32),
    ("EDMA_0_CH3", 4u32),
    ("EDMA_0_CH4", 5u32),
    ("EDMA_0_CH5", 6u32),
    ("EDMA_0_CH6", 7u32),
    ("EDMA_0_CH7", 8u32),
    ("EDMA_0_CH8", 9u32),
    ("EDMA_0_CH9", 10u32),
    ("EDMA_0_CH10", 11u32),
    ("EDMA_0_CH11", 12u32),
    ("EDMA_0_CH12", 13u32),
    ("EDMA_0_CH13", 14u32),
    ("EDMA_0_CH14", 15u32),
    ("EDMA_0_CH15", 16u32),
    ("EDMA_1_CH0", 77u32),
    ("EDMA_1_CH1", 78u32),
    ("EDMA_1_CH2", 79u32),
    ("EDMA_1_CH3", 80u32),
    ("EDMA_1_CH4", 81u32),
    ("EDMA_1_CH5", 82u32),
    ("EDMA_1_CH6", 83u32),
    ("EDMA_1_CH7", 84u32),
    ("EDMA_1_CH8", 85u32),
    ("EDMA_1_CH9", 86u32),
    ("EDMA_1_CH10", 87u32),
    ("EDMA_1_CH11", 88u32),
    ("EDMA_1_CH12", 89u32),
    ("EDMA_1_CH13", 90u32),
    ("EDMA_1_CH14", 91u32),
    ("EDMA_1_CH15", 92u32),
    ("SCT0", 33u32),
    ("LP_FLEXCOMM0", 35u32),
    ("LP_FLEXCOMM1", 36u32),
    ("LP_FLEXCOMM2", 37u32),
    ("LP_FLEXCOMM3", 38u32),
    ("LP_FLEXCOMM4", 39u32),
    ("LP_FLEXCOMM5", 40u32),
    ("LP_FLEXCOMM6", 41u32),
    ("LP_FLEXCOMM7", 42u32),
    ("LP_FLEXCOMM8", 43u32),
    ("LP_FLEXCOMM9", 44u32),
    ("GPIO00", 17u32),
    ("GPIO01", 18u32),
    ("GPIO10", 19u32),
    ("GPIO11", 20u32),
    ("GPIO20", 21u32),
    ("GPIO21", 22u32),
    ("GPIO30", 23u32),
    ("GPIO31", 24u32),
    ("GPIO40", 25u32),
    ("GPIO41", 26u32),
    ("MAILBOX", 54u32),
    ("CDOG0", 93u32),
    ("CDOG1", 94u32),
    ("PQ", 76u32),
    ("EWM0", 100u32),
    ("SEC_VIO", 72u32),
    ("FLEXSPI0", 58u32),
    ("FLEXPWM0_RELOAD_ERROR", 112u32),
    ("FLEXPWM0_FAULT", 113u32),
    ("FLEXPWM0_SUBMODULE0", 114u32),
    ("FLEXPWM0_SUBMODULE1", 115u32),
    ("FLEXPWM0_SUBMODULE2", 116u32),
    ("FLEXPWM0_SUBMODULE3", 117u32),
    ("FLEXPWM1_RELOAD_ERROR", 118u32),
    ("FLEXPWM1_FAULT", 119u32),
    ("FLEXPWM1_SUBMODULE0", 120u32),
    ("FLEXPWM1_SUBMODULE1", 121u32),
    ("FLEXPWM1_SUBMODULE2", 122u32),
    ("FLEXPWM1_SUBMODULE3", 123u32),
    ("QDC0_COMPARE", 124u32),
    ("QDC0_HOME", 125u32),
    ("QDC0_WDG_SAB", 126u32),
    ("QDC0_IDX", 127u32),
    ("QDC1_COMPARE", 128u32),
    ("QDC1_HOME", 129u32),
    ("QDC1_WDG_SAB", 130u32),
    ("QDC1_IDX", 131u32),
    ("CAN0", 62u32),
    ("CAN1", 63u32),
    ("USB0_DCD", 51u32),
    ("USB0_FS", 50u32),
    ("ETHERNET", 139u32),
    ("ETHERNET_PMT", 140u32),
    ("ETHERNET_MACLP", 141u32),
    ("EMVSIM0", 103u32),
    ("EMVSIM1", 104u32),
    ("FLEXIO", 105u32),
    ("SAI0", 59u32),
    ("SAI1", 60u32),
    ("SINC_FILTER", 142u32),
    ("USDHC0", 61u32),
    ("USB1_HS_PHY", 66u32),
    ("USB1_HS", 67u32),
    ("PDM_EVENT", 48u32),
    ("ADC0", 45u32),
    ("ADC1", 46u32),
    ("DAC0", 106u32),
    ("DAC1", 107u32),
    ("DAC2", 108u32),
    ("SEC_HYPERVISOR_CALL", 68u32),
    ("OR", 0u32),
    ("RESERVED65", 49u32),
    ("RESERVED80", 64u32),
    ("RESERVED81", 65u32),
    ("RESERVED85", 69u32),
    ("NPU", 97u32),
    ("RESERVED166", 150u32),
    ("RESERVED167", 151u32),
];
