use crate::metadata::*;
pub const METADATA: Metadata = Metadata {
    name: "MCXN947_cm33_core1",
    pins: PINS,
    peripherals: PERIPHERALS,
    interrupts: INTERRUPTS,
};
pub const PINS: &[Pin] = &[];
pub const PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "SYSCON0",
        address: 0x40000000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PINT0",
        address: 0x40004000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "INPUTMUX0",
        address: 0x40006000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CTIMER0",
        address: 0x4000C000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CTIMER1",
        address: 0x4000D000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CTIMER2",
        address: 0x4000E000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CTIMER3",
        address: 0x4000F000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CTIMER4",
        address: 0x40010000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FREQME0",
        address: 0x40011000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "UTICK0",
        address: 0x40012000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "MRT0",
        address: 0x40013000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "WWDT0",
        address: 0x40016000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "WWDT1",
        address: 0x40017000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CACHE64_CTRL0",
        address: 0x4001B000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CACHE64_POLSEL0",
        address: 0x4001B000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "I3C0",
        address: 0x40021000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "I3C1",
        address: 0x40022000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GDET0",
        address: 0x40024000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GDET1",
        address: 0x40025000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ITRC0",
        address: 0x40026000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PKC0",
        address: 0x4002B000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF",
        address: 0x4002C000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_ALIAS1",
        address: 0x4002D000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_ALIAS2",
        address: 0x4002E000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_ALIAS3",
        address: 0x4002F000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_CTRL",
        address: 0x4002C000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_CTRL_ALIAS1",
        address: 0x4002D000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_CTRL_ALIAS2",
        address: 0x4002E000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PUF_CTRL_ALIAS3",
        address: 0x4002F000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "BSP32_0",
        address: 0x40032000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SMARTDMA0",
        address: 0x40033000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PLU0",
        address: 0x40034000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO5",
        address: 0x40040000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO5_ALIAS1",
        address: 0x40041000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT5",
        address: 0x40042000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FMU0",
        address: 0x40043000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FMU0TEST",
        address: 0x40043000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SCG0",
        address: 0x40044000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SPC0",
        address: 0x40045000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "WUU0",
        address: 0x40046000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMC0",
        address: 0x40048000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "OSTIMER0",
        address: 0x40049000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPTMR0",
        address: 0x4004A000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPTMR1",
        address: 0x4004B000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "RTC0",
        address: 0x4004C000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "RTC_SUBSYSTEM0",
        address: 0x4004C000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "TSI0",
        address: 0x40050000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMP0",
        address: 0x40051000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMP1",
        address: 0x40052000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMP2",
        address: 0x40053000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ELS",
        address: 0x40054000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ELS_ALIAS1",
        address: 0x40055000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ELS_ALIAS2",
        address: 0x40056000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ELS_ALIAS3",
        address: 0x40057000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "TDET0",
        address: 0x40058000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "VBAT0",
        address: 0x40059000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EIM0",
        address: 0x4005B000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ERM0",
        address: 0x4005C000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "INTM0",
        address: 0x4005D000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EDMA_0_TCD",
        address: 0x40081000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SCT0",
        address: 0x40091000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI0",
        address: 0x40092000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI1",
        address: 0x40093000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI2",
        address: 0x40094000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI3",
        address: 0x40095000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI4",
        address: 0x400B4000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI5",
        address: 0x400B5000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI6",
        address: 0x400B6000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI7",
        address: 0x400B7000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI8",
        address: 0x400B8000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPSPI9",
        address: 0x400B9000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART0",
        address: 0x40092000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART1",
        address: 0x40093000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART2",
        address: 0x40094000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART3",
        address: 0x40095000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART4",
        address: 0x400B4000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART5",
        address: 0x400B5000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART6",
        address: 0x400B6000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART7",
        address: 0x400B7000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART8",
        address: 0x400B8000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPUART9",
        address: 0x400B9000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM0",
        address: 0x40092000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM1",
        address: 0x40093000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM2",
        address: 0x40094000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM3",
        address: 0x40095000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM4",
        address: 0x400B4000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM5",
        address: 0x400B5000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM6",
        address: 0x400B6000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM7",
        address: 0x400B7000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM8",
        address: 0x400B8000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LP_FLEXCOMM9",
        address: 0x400B9000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C0",
        address: 0x40092800,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C1",
        address: 0x40093800,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C2",
        address: 0x40094800,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C3",
        address: 0x40095800,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C4",
        address: 0x400B4800,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C5",
        address: 0x400B5800,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C6",
        address: 0x400B6800,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C7",
        address: 0x400B7800,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C8",
        address: 0x400B8800,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "LPI2C9",
        address: 0x400B9800,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO0",
        address: 0x40096000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO0_ALIAS1",
        address: 0x40097000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO1",
        address: 0x40098000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO1_ALIAS1",
        address: 0x40099000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO2",
        address: 0x4009A000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO2_ALIAS1",
        address: 0x4009B000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO3",
        address: 0x4009C000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO3_ALIAS1",
        address: 0x4009D000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO4",
        address: 0x4009E000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO4_ALIAS1",
        address: 0x4009F000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EDMA_1_TCD",
        address: 0x400A1000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SEMA42_0",
        address: 0x400B1000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "MAILBOX",
        address: 0x400B2000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CDOG0",
        address: 0x400BB000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CDOG1",
        address: 0x400BC000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DM0",
        address: 0x400BD000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "POWERQUAD",
        address: 0x400BF000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EWM0",
        address: 0x400C0000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMX_PERFMON0",
        address: 0x400C1000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMX_PERFMON1",
        address: 0x400C2000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "TRDC",
        address: 0x400C7000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FLEXSPI0",
        address: 0x400C8000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "OTPC0",
        address: 0x400C9000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CRC0",
        address: 0x400CB000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "NPX0",
        address: 0x400CC000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PWM0",
        address: 0x400CE000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PWM1",
        address: 0x400D0000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "QDC0",
        address: 0x400CF000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "QDC1",
        address: 0x400D1000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EVTG0",
        address: 0x400D2000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CAN0",
        address: 0x400D4000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CAN1",
        address: 0x400D8000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBDCD0",
        address: 0x400DC000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBFS0",
        address: 0x400DD000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ENET0",
        address: 0x40100000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EMVSIM0",
        address: 0x40103000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EMVSIM1",
        address: 0x40104000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FLEXIO0",
        address: 0x40105000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SAI0",
        address: 0x40106000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SAI1",
        address: 0x40107000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SINC0",
        address: 0x40108000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USDHC0",
        address: 0x40109000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBPHY",
        address: 0x4010A000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBHS1_PHY_DCD",
        address: 0x4010A800,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBHS1__USBC",
        address: 0x4010B000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "USBHS1__USBNC",
        address: 0x4010B200,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PDM",
        address: 0x4010C000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ADC0",
        address: 0x4010D000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ADC1",
        address: 0x4010E000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DAC0",
        address: 0x4010F000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DAC1",
        address: 0x40112000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "OPAMP0",
        address: 0x40110000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "OPAMP1",
        address: 0x40113000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "OPAMP2",
        address: 0x40115000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "VREF0",
        address: 0x40111000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DAC2",
        address: 0x40114000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT0",
        address: 0x40116000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT1",
        address: 0x40117000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT2",
        address: 0x40118000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT3",
        address: 0x40119000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT4",
        address: 0x4011A000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "AHBSC",
        address: 0x40120000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "AHBSC_ALIAS1",
        address: 0x40121000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "AHBSC_ALIAS2",
        address: 0x40122000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "AHBSC_ALIAS3",
        address: 0x40123000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SCnSCB",
        address: 0xE000E000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SysTick0",
        address: 0xE000E010,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "NVIC",
        address: 0xE000E100,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SCB",
        address: 0xE000ED00,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "MPU",
        address: 0xE000ED90,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SAU",
        address: 0xE000EDD0,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
];
pub const INTERRUPTS: &[(&str, u32)] = &[
    ("ETB0", 149u32),
    ("CTI0", 155u32),
    ("PINT0", 47u32),
    ("CTIMER0", 31u32),
    ("CTIMER1", 32u32),
    ("CTIMER2", 34u32),
    ("CTIMER3", 55u32),
    ("CTIMER4", 56u32),
    ("FREQME", 71u32),
    ("UTICK0", 29u32),
    ("MRT0", 30u32),
    ("WWDT0", 152u32),
    ("WWDT1", 153u32),
    ("I3C0", 95u32),
    ("I3C1", 96u32),
    ("GDET", 98u32),
    ("ITRC0", 132u32),
    ("PKC", 74u32),
    ("PKC_ERR", 135u32),
    ("PUF", 75u32),
    ("BSP32", 133u32),
    ("SMARTDMA", 53u32),
    ("PLU", 70u32),
    ("GPIO50", 27u32),
    ("GPIO51", 28u32),
    ("PORT_EFT", 148u32),
    ("FMU0", 138u32),
    ("SCG", 145u32),
    ("SPC", 146u32),
    ("WUU", 147u32),
    ("CMC0", 154u32),
    ("OS_EVENT", 57u32),
    ("LPTMR0", 143u32),
    ("LPTMR1", 144u32),
    ("RTC", 52u32),
    ("TSI_END_OF_SCAN", 101u32),
    ("TSI_OUT_OF_SCAN", 102u32),
    ("HSCMP0", 109u32),
    ("HSCMP1", 110u32),
    ("HSCMP2", 111u32),
    ("ELS", 73u32),
    ("ELS_ERR", 134u32),
    ("VBAT0", 99u32),
    ("ERM_SINGLE_BIT_ERROR", 136u32),
    ("ERM_MULTI_BIT_ERROR", 137u32),
    ("EDMA_0_CH0", 1u32),
    ("EDMA_0_CH1", 2u32),
    ("EDMA_0_CH2", 3u32),
    ("EDMA_0_CH3", 4u32),
    ("EDMA_0_CH4", 5u32),
    ("EDMA_0_CH5", 6u32),
    ("EDMA_0_CH6", 7u32),
    ("EDMA_0_CH7", 8u32),
    ("EDMA_0_CH8", 9u32),
    ("EDMA_0_CH9", 10u32),
    ("EDMA_0_CH10", 11u32),
    ("EDMA_0_CH11", 12u32),
    ("EDMA_0_CH12", 13u32),
    ("EDMA_0_CH13", 14u32),
    ("EDMA_0_CH14", 15u32),
    ("EDMA_0_CH15", 16u32),
    ("EDMA_1_CH0", 77u32),
    ("EDMA_1_CH1", 78u32),
    ("EDMA_1_CH2", 79u32),
    ("EDMA_1_CH3", 80u32),
    ("EDMA_1_CH4", 81u32),
    ("EDMA_1_CH5", 82u32),
    ("EDMA_1_CH6", 83u32),
    ("EDMA_1_CH7", 84u32),
    ("EDMA_1_CH8", 85u32),
    ("EDMA_1_CH9", 86u32),
    ("EDMA_1_CH10", 87u32),
    ("EDMA_1_CH11", 88u32),
    ("EDMA_1_CH12", 89u32),
    ("EDMA_1_CH13", 90u32),
    ("EDMA_1_CH14", 91u32),
    ("EDMA_1_CH15", 92u32),
    ("SCT0", 33u32),
    ("LP_FLEXCOMM0", 35u32),
    ("LP_FLEXCOMM1", 36u32),
    ("LP_FLEXCOMM2", 37u32),
    ("LP_FLEXCOMM3", 38u32),
    ("LP_FLEXCOMM4", 39u32),
    ("LP_FLEXCOMM5", 40u32),
    ("LP_FLEXCOMM6", 41u32),
    ("LP_FLEXCOMM7", 42u32),
    ("LP_FLEXCOMM8", 43u32),
    ("LP_FLEXCOMM9", 44u32),
    ("GPIO00", 17u32),
    ("GPIO01", 18u32),
    ("GPIO10", 19u32),
    ("GPIO11", 20u32),
    ("GPIO20", 21u32),
    ("GPIO21", 22u32),
    ("GPIO30", 23u32),
    ("GPIO31", 24u32),
    ("GPIO40", 25u32),
    ("GPIO41", 26u32),
    ("MAILBOX", 54u32),
    ("CDOG0", 93u32),
    ("CDOG1", 94u32),
    ("PQ", 76u32),
    ("EWM0", 100u32),
    ("SEC_VIO", 72u32),
    ("FLEXSPI0", 58u32),
    ("FLEXPWM0_RELOAD_ERROR", 112u32),
    ("FLEXPWM0_FAULT", 113u32),
    ("FLEXPWM0_SUBMODULE0", 114u32),
    ("FLEXPWM0_SUBMODULE1", 115u32),
    ("FLEXPWM0_SUBMODULE2", 116u32),
    ("FLEXPWM0_SUBMODULE3", 117u32),
    ("FLEXPWM1_RELOAD_ERROR", 118u32),
    ("FLEXPWM1_FAULT", 119u32),
    ("FLEXPWM1_SUBMODULE0", 120u32),
    ("FLEXPWM1_SUBMODULE1", 121u32),
    ("FLEXPWM1_SUBMODULE2", 122u32),
    ("FLEXPWM1_SUBMODULE3", 123u32),
    ("QDC0_COMPARE", 124u32),
    ("QDC0_HOME", 125u32),
    ("QDC0_WDG_SAB", 126u32),
    ("QDC0_IDX", 127u32),
    ("QDC1_COMPARE", 128u32),
    ("QDC1_HOME", 129u32),
    ("QDC1_WDG_SAB", 130u32),
    ("QDC1_IDX", 131u32),
    ("CAN0", 62u32),
    ("CAN1", 63u32),
    ("USB0_DCD", 51u32),
    ("USB0_FS", 50u32),
    ("ETHERNET", 139u32),
    ("ETHERNET_PMT", 140u32),
    ("ETHERNET_MACLP", 141u32),
    ("EMVSIM0", 103u32),
    ("EMVSIM1", 104u32),
    ("FLEXIO", 105u32),
    ("SAI0", 59u32),
    ("SAI1", 60u32),
    ("SINC_FILTER", 142u32),
    ("USDHC0", 61u32),
    ("USB1_HS_PHY", 66u32),
    ("USB1_HS", 67u32),
    ("PDM_EVENT", 48u32),
    ("ADC0", 45u32),
    ("ADC1", 46u32),
    ("DAC0", 106u32),
    ("DAC1", 107u32),
    ("DAC2", 108u32),
    ("SEC_HYPERVISOR_CALL", 68u32),
    ("OR", 0u32),
    ("RESERVED65", 49u32),
    ("RESERVED80", 64u32),
    ("RESERVED81", 65u32),
    ("RESERVED85", 69u32),
    ("NPU", 97u32),
    ("RESERVED166", 150u32),
    ("RESERVED167", 151u32),
];
